"""Add budget uniqueness constraint

Revision ID: 338730a93a45
Revises: 
Create Date: 2026-09-01 22:32:55.206147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338730a93a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint('unique_user_budget', ['user_id', 'month', 'year', 'category'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_budget', type_='unique')
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
